const fs=require('fs')
let filecontent=fs.readFileSync('f1.txt')
// console.log('output'+filecontent)
// let filecontent1=fs.writeFileSync('f1.txt','this is file')
// console.log('output'+filecontent)
// let filecontent3=fs.appendFileSync('f1.txt','this is file')
// console.log('output'+filecontent)
let filecontent4=fs.unlinkSync('f1.txt')
console.log('output'+filecontent)